### ISSUE TITLE
YouTube ID too long causes overflowing

### ISSUE THREAD

**Issue by RayBB** [fuddl/wikibase-for-web#4]
It causes a bit of overflowing. Should be a pretty easy CSS fix if someone knows where to look.

<img width="319" alt="Screenshot 2024-11-19 at 21 06 45" src="https://github.com/user-attachments/assets/a24e4194-c204-4691-9136-ef309f55a90e">

**Comment by fuddl** [comment]
Should be fixed in version `.622` by allowing line breaks in every id: 

![YouTube channel ID (line break) UCEw0sdrCOjcsjtXGJ(line break)ibItJA](https://github.com/user-attachments/assets/8ab63468-88c2-419c-b98f-05d2cd7f15b8)

@RayBB  Please close the issue, if you agree. 😀

**Comment by RayBB** [comment]
Looks great thanks!
